name: Deploy to Cloud Server

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Select the service to deploy"
        required: true
        type: choice
        options:
          - api
          - frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to Alibaba Cloud Docker Registry
        if: ${{ github.event.inputs.service == 'api' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_DOCKER_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKER_USER }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        if: ${{ github.event.inputs.service == 'api' }}
        run: |
          cd $GITHUB_WORKSPACE/backend && bash ./hack/image-build-and-push.sh ${{ github.event.inputs.service }}

      - name: SSH and deploy API on server
        if: ${{ github.event.inputs.service == 'api' }}
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/hack
            bash docker-run.sh ${{ github.event.inputs.service }}

      - name: Install dependencies and build Vue project
        if: ${{ github.event.inputs.service == 'frontend' }}
        run: |
          cd $GITHUB_WORKSPACE/frontend
          npm ci
          npm run build

      - name: Upload Vue dist to server
        if: ${{ github.event.inputs.service == 'frontend' }}
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./frontend/dist/*"
          target: "~/frontend/dist/"
